CREATE TABLE IF NOT EXISTS topicos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(160) NOT NULL,
  mensaje TEXT NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(30) NOT NULL,
  autor VARCHAR(120) NOT NULL,
  curso VARCHAR(120) NOT NULL
) ENGINE=InnoDB;
