CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  clave VARCHAR(255) NOT NULL,
  rol VARCHAR(30) NOT NULL DEFAULT 'USER',
  activo BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;